#!/usr/bin/ruby

REGISTER_TABLE = {}
REGISTER_TABLE["A"]  = 0
REGISTER_TABLE["X"]  = 1
REGISTER_TABLE["L"]  = 2
REGISTER_TABLE["B"]  = 3
REGISTER_TABLE["S"]  = 4
REGISTER_TABLE["T"]  = 5
REGISTER_TABLE["F"]  = 6
REGISTER_TABLE["PC"] = 8
REGISTER_TABLE["SW"] = 9
